name: Sync SukkaW DNS Mapping

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  sync-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Clean DNS Rules
        run: |
          # 创建目标目录
          TARGET_DIR="Tool/Egern/Rules"
          mkdir -p "$TARGET_DIR"

          # 定义下载列表
          urls=(
            "https://ruleset.skk.moe/Modules/Rules/sukka_local_dns_mapping/alibaba.conf"
            "https://ruleset.skk.moe/Modules/Rules/sukka_local_dns_mapping/tencent.conf"
            "https://ruleset.skk.moe/Modules/Rules/sukka_local_dns_mapping/bilibili.conf"
            "https://ruleset.skk.moe/Modules/Rules/sukka_local_dns_mapping/bytedance.conf"
            "https://ruleset.skk.moe/Modules/Rules/sukka_local_dns_mapping/baidu.conf"
          )

          # 循环下载并即时清理
          for url in "${urls[@]}"; do
            raw_name=$(basename "$url")
            # 将首字母转换为大写
            filename="${raw_name^}"
            
            echo "Processing $raw_name -> $filename..."
            
            # 下载文件
            curl -L "$url" -o "$TARGET_DIR/$filename"

            # 执行删除指定域名的操作
            sed -i -e '/this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "$TARGET_DIR/$filename"
            sed -i -e '/th1s_rule5et_1s_m4d3_by_5ukk4w_ruleset.skk.moe/d' "$TARGET_DIR/$filename"
            sed -i -e '/this_rule_set_is_made_by_sukkaw.skk.moe/d' "$TARGET_DIR/$filename"
            sed -i -e '/7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe/d' "$TARGET_DIR/$filename"
          done

      - name: Push Update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Tool/Egern/Rules/
          
          # 检查是否有文件变动并提交
          if [[ -n $(git status -s) ]]; then
            git commit -m "Update(DNS): Sync SukkaW DNS mapping $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected."
          fi
