name: Update CN Domain Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v3

      - name: Download and Process
        run: |
          # 1. 下载上游文件
          curl -sSL https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/refs/heads/main/GeositeCN/GeositeCN.yaml -o raw_cn.txt
          
          # 2. 确保目标文件夹存在 (根据你的截图路径)
          mkdir -p Tool/Egern/Rules/
          
          # 3. 处理规则并直接输出到指定文件夹
          grep "DOMAIN-SUFFIX" raw_cn.txt | \
          sed -E 's/^[[:space:]]*-?[[:space:]]*//g' | \
          sed 's/ //g' | \
          sed 's/#.*//g' | \
          sort -u > Tool/Egern/Rules/MyChinaDomain.list

      - name: Git Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          # 添加指定目录下的文件
          git add Tool/Egern/Rules/MyChinaDomain.list
          git commit -m "自动更新规则至 Rules 目录: $(date +%Y-%m-%d)" || exit 0
          git push
