name: Update CN Domain Rules

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v3

      - name: Download and Process
        run: |
          curl -sSL https://raw.githubusercontent.com/Accademia/Additional_Rule_For_Clash/refs/heads/main/GeositeCN/GeositeCN.yaml -o raw_cn.txt
          
          mkdir -p Tool/Egern/Rules/
          
          grep "DOMAIN" raw_cn.txt | \
          sed -E 's/^[[:space:]]*-?[[:space:]]*//g' | \
          sed 's/ //g' | \
          sed 's/#.*//g' | \
          sort -u > temp.txt
          
          COUNT=$(wc -l < temp.txt)
          
          # 构建最终文件
          echo "# 规则名称: MyChinaDomain" > Tool/Egern/Rules/MyChinaDomain.list
          echo "# 规则统计: $COUNT" >> Tool/Egern/Rules/MyChinaDomain.list
          # 通过 printf 合并日期和空行，严格控制换行数量
          printf "# 最后更新: $(date '+%Y-%m-%d %H:%M:%S') (GMT)\n\n" >> Tool/Egern/Rules/MyChinaDomain.list
          cat temp.txt >> Tool/Egern/Rules/MyChinaDomain.list

      - name: Git Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add Tool/Egern/Rules/MyChinaDomain.list
          git commit -m "优化排版格式(解决多余空行): $(date +%Y-%m-%d %H:%M:%S)" || exit 0
          git push
